---
site_name: Второй мозг
site_description: Сайт моих заметок
site_author: Evgeniy Dorovatovskiy
nav:
  - Разработка:
    - Асинхронность: async.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
#
repo_name: gitex/second-brain
repo_url: https://github.com/gitex/second-brain
