---
site_name: Второй мозг
site_description: Сайт моих заметок
site_author: Evgeniy Dorovatovskiy
site_url: https://gitex.github.io/wiki/
nav:
  - Языки программирования:
    - Python:
      - coding/python/index.md
      - Оптимизация: coding/python/optimization.md
      - Pytest: coding/python/pytest.md
      - __add__ и __radd__: coding/python/__add__.md
      - Библиотека на Rust: coding/python/rust_library.md
      - Освобождение памяти: coding/python/memory.md
    - Git:
      - Conventional Commits: coding/conventional_commits.md

  - Асинхронность: coding/async.md
  - Кэширование:
    - Громовое стадо: coding/cache/thundering_herd.md
    - Негативное кэширование: coding/cache/negative_cache.md
    - Джиттер: coding/cache/jitter.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - tags
  - offline
  - meta

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css: [stylesheets/extra.css]

repo_name: gitex/wiki
repo_url: https://github.com/gitex/wiki

